// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func InitialiseService() Service {
	db := NewDB()
	service := NewService(db)
	return service
}
